// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package handler

import (
	"net/http"

	"tiktokShop/auth/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/deliver",
				Handler: DeliverTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/verify",
				Handler: VerifyTokenHandler(serverCtx),
			},
		},
	)
}
