// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: auth.proto

package server

import (
	"context"

	"tiktokShop/auth/rpc/auth"
	"tiktokShop/auth/rpc/internal/logic"
	"tiktokShop/auth/rpc/internal/svc"
)

type AuthServiceServer struct {
	svcCtx *svc.ServiceContext
	auth.UnimplementedAuthServiceServer
}

func NewAuthServiceServer(svcCtx *svc.ServiceContext) *AuthServiceServer {
	return &AuthServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServiceServer) DeliverTokenByRPC(ctx context.Context, in *auth.DeliverTokenReq) (*auth.DeliveryResp, error) {
	l := logic.NewDeliverTokenByRPCLogic(ctx, s.svcCtx)
	return l.DeliverTokenByRPC(in)
}

func (s *AuthServiceServer) VerifyTokenByRPC(ctx context.Context, in *auth.VerifyTokenReq) (*auth.VerifyResp, error) {
	l := logic.NewVerifyTokenByRPCLogic(ctx, s.svcCtx)
	return l.VerifyTokenByRPC(in)
}
