// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type ChargeRequest struct {
	Amount     float64        `json:"amount"`
	CreditCard CreditCardInfo `json:"creditCard"`
	OrderId    string         `json:"orderId"`
	UserId     uint32         `json:"userId"`
}

type ChargeResponse struct {
	TransactionId string `json:"transactionId"`
}

type CreditCardInfo struct {
	CreditCardNumber          string `json:"creditCardNumber"`
	CreditCardCvv             int32  `json:"creditCardCvv"`
	CreditCardExpirationYear  int32  `json:"creditCardExpirationYear"`
	CreditCardExpirationMonth int32  `json:"creditCardExpirationMonth"`
}
