// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type AddItemReq struct {
	UserId uint32   `json:"user_id"`
	Item   CartItem `json:"item"`
}

type AddItemResp struct {
}

type Cart struct {
	UserId uint32     `json:"user_id"`
	Items  []CartItem `json:"items"`
}

type CartItem struct {
	ProductId uint32 `json:"product_id"`
	Quantity  int32  `json:"quantity"`
}

type EmptyCartReq struct {
	UserId uint32 `json:"user_id"`
}

type EmptyCartResp struct {
}

type GetCartReq struct {
	UserId uint32 `json:"user_id"`
}

type GetCartResp struct {
	Cart Cart `json:"cart"`
}
