// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: payment.proto

package server

import (
	"context"

	"tiktokShop/payment/rpc/internal/logic"
	"tiktokShop/payment/rpc/internal/svc"
	"tiktokShop/payment/rpc/payment"
)

type PaymentServiceServer struct {
	svcCtx *svc.ServiceContext
	payment.UnimplementedPaymentServiceServer
}

func NewPaymentServiceServer(svcCtx *svc.ServiceContext) *PaymentServiceServer {
	return &PaymentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PaymentServiceServer) Charge(ctx context.Context, in *payment.ChargeReq) (*payment.ChargeResp, error) {
	l := logic.NewChargeLogic(ctx, s.svcCtx)
	return l.Charge(in)
}
