// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type DeliverTokenRequest struct {
	UserId int32 `json:"userId"`
}

type DeliverTokenResponse struct {
	Token string `json:"token"`
}

type VerifyTokenRequest struct {
	Token string `json:"token"`
}

type VerifyTokenResponse struct {
	Res bool `json:"res"`
}
