// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type GetProductReq struct {
	Id uint32 `path:"id"`
}

type GetProductResp struct {
	Product Product `json:"product"`
}

type ListProductsReq struct {
	Page         int32  `json:"page"`
	PageSize     int64  `json:"pageSize"`
	CategoryName string `json:"categoryName"`
}

type ListProductsResp struct {
	Products []Product `json:"products"`
}

type Product struct {
	Id          uint32   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Picture     string   `json:"picture"`
	Price       float64  `json:"price"`
	Categories  []string `json:"categories"`
}

type SearchProductsReq struct {
	Query string `json:"query"`
}

type SearchProductsResp struct {
	Results []Product `json:"results"`
}
