// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: payment.proto

package paymentservice

import (
	"context"

	"tiktokShop/payment/rpc/payment"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChargeReq      = payment.ChargeReq
	ChargeResp     = payment.ChargeResp
	CreditCardInfo = payment.CreditCardInfo

	PaymentService interface {
		Charge(ctx context.Context, in *ChargeReq, opts ...grpc.CallOption) (*ChargeResp, error)
	}

	defaultPaymentService struct {
		cli zrpc.Client
	}
)

func NewPaymentService(cli zrpc.Client) PaymentService {
	return &defaultPaymentService{
		cli: cli,
	}
}

func (m *defaultPaymentService) Charge(ctx context.Context, in *ChargeReq, opts ...grpc.CallOption) (*ChargeResp, error) {
	client := payment.NewPaymentServiceClient(m.cli.Conn())
	return client.Charge(ctx, in, opts...)
}
