// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package handler

import (
	"net/http"

	"tiktokShop/cart/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/cart/add",
				Handler: AddItemHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/cart/empty",
				Handler: EmptyCartHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/cart/get",
				Handler: GetCartHandler(serverCtx),
			},
		},
	)
}
